services:
  gridscope:
    build: .
    container_name: gridscope_system
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./dados:/app/dados
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped